[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  BUN_VERSION = "1.0.0"  # sesuaikan dengan versi Bun Anda

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200