name: Deploy
on:
  push:
    branches: [ main ] # atau master, sesuaikan dengan branch Anda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "backendiot" # Ganti dengan nama project Anda di Deno Deploy
          entrypoint: "src/index.ts" # Sesuaikan dengan file entry point Anda
